---
sidebar: sidebar 
permalink: get-started/requirements.html 
keywords: what are astra kubernetes requirements, astra control requirements, astra supported versions, apps, supported apps, mariadb, mysql, postgres, kubernetes version, ubuntu, image type, networking 
summary: Kubernetes 클러스터, 앱 및 웹 브라우저에 대한 지원을 확인하여 Astra Control Center를 시작하십시오. 
---
= Astra Control Center 요구 사항
:hardbreaks:
:icons: font
:imagesdir: ../media/get-started/


Kubernetes 클러스터, 앱, 라이센스 및 웹 브라우저에 대한 지원을 확인하여 시작하십시오.



== Kubernetes 클러스터 일반 요구사항

Kubernetes 클러스터는 Astra Control Center에서 검색 및 관리할 수 있도록 다음과 같은 일반 요구사항을 충족해야 합니다.

* * 이미지 레지스트리 *: Astra Control Center 빌드 이미지를 푸시할 수 있는 기존 개인 Docker 이미지 레지스트리가 있어야 합니다. 이미지를 업로드할 이미지 레지스트리의 URL이 있어야 하며 개인 컨테이너 레지스트리의 이미지에 태그를 지정해야 합니다.
* * Trident/ONTAP 스토리지 구성 *:Astra Control Center에서는 Trident 버전 21.01 또는 21.04가 이미 설치되어 스토리지 백엔드로 NetApp ONTAP 버전 9.5 이상에서 작동하도록 구성해야 합니다. Astra Control Center에서는 스토리지 클래스를 생성하고 기본 스토리지 클래스로 설정해야 합니다. Astra Control Center는 Trident에서 제공하는 다음과 같은 ONTAP 드라이버를 지원합니다.
+
** ONTAP - NAS
** ONTAP-NAS-Flexgroup입니다
** ONTAP-SAN
** ONTAP-SAN - 경제성




Astra Control Center에서 Kubernetes 클러스터를 관리하고 클러스터를 사용하여 Astra Control Center 설치를 호스트하려는 경우 클러스터에 다음과 같은 추가 요구사항이 있습니다.

* Kubernetes의 최신 버전입니다 https://kubernetes-csi.github.io/docs/snapshot-controller.html["스냅샷 컨트롤러 구성 요소입니다"^] 이(가) 설치되었습니다
* 트라이던트 https://netapp-trident.readthedocs.io/en/latest/kubernetes/concepts/objects.html?highlight=VolumeSnapshotClass#kubernetes-volumesnapshotclass-objects["볼륨스냅샷 클래스 개체"^] 관리자가 정의했습니다
* 클러스터에 기본 Kubernetes 스토리지 클래스가 있습니다
* Trident를 사용하도록 스토리지 클래스가 하나 이상 구성되었습니다
* Astra Control Center의 FQDN을 Astra Control Center 서비스의 외부 IP 주소로 가리키는 방법




=== OpenShift 클러스터

Astra Control Center에는 ONTAP 9.5 이상 버전에서 지원하는 Trident 스토리지 클래스가 있는 Red Hat OpenShift Container Platform 4.6.8 또는 4.7 클러스터가 필요합니다. 이러한 특성은 다음과 같습니다.

* 최소 300GB의 가용 ONTAP 스토리지 용량
* 3개의 컨트롤러 노드에서 4개의 CPU 코어, 16GB RAM 및 120GB의 사용 가능한 스토리지
* 최소 12개의 CPU 코어, 32GB RAM 및 50GB의 가용 스토리지를 갖춘 3개의 작업자 노드
* Kubernetes 버전 1.19 또는 1.20
* OpenShift 클러스터의 서비스로 수신 트래픽을 보내는 데 사용할 수 있는 서비스 유형 "로드 밸런서"입니다
* Astra Control Center의 FQDN을 부하 분산 IP 주소로 가리키는 방법



NOTE: 이러한 최소 요구 사항은 Astra Control Center가 OpenShift 클러스터에서 실행되는 유일한 애플리케이션이라고 가정합니다. 클러스터에서 추가 애플리케이션이 실행 중인 경우 이러한 최소 요구사항을 적절히 조정해야 합니다.

클러스터가 최소 요구사항을 충족하고 Kubernetes 모범 사례를 따르는 경우 Kubernetes 클러스터에서 Astra Control Center의 가용성이 높도록 하십시오.


NOTE: OpenShift 4.8은 지원되지 않습니다.

[NOTE]
====
애플리케이션 복제 중에 Astra Control Center는 OpenShift가 볼륨을 마운트하고 파일 소유권을 변경할 수 있도록 허용해야 합니다. 따라서 다음 명령을 사용하여 볼륨 작업을 성공적으로 완료할 수 있도록 ONTAP를 구성해야 합니다.

. 'export-policy rule modify -vserver svm0 -policyname default-ruleindex 1 -superuser sys'
. 수출정책규칙 수정-정책명 default-ruleindex 1-anon 65534


====

NOTE: 두 번째 OpenShift 4.6 또는 4.7 클러스터를 관리되는 컴퓨팅 리소스로 추가하려면 Trident Volume Snapshot 기능이 활성화되어 있는지 확인해야 합니다. 공식 Trident를 참조하십시오 https://netapp-trident.readthedocs.io/en/stable-v21.04/kubernetes/operations/tasks/volumes/snapshots.html?highlight=volumesnapshot#on-demand-volume-snapshots["지침"^] Trident를 사용하여 볼륨 스냅샷을 활성화하고 테스트합니다.



=== 설명합니다

Astra Control Center에는 다음과 같은 앱 관리 요구 사항이 있습니다.

* * 라이선스 *: Astra Control Center를 사용하여 앱을 관리하려면 Astra Control Center 라이센스가 필요합니다.
* * Helm 3 *: Helm을 사용하여 앱을 배포하는 경우 Astra Control Center에 Helm 버전 3이 필요합니다. Helm 3으로 배포된 애플리케이션 관리 및 복제(또는 Helm 2에서 Helm 3으로 업그레이드)가 완벽하게 지원됩니다. Helm 2와 함께 배포된 앱은 지원되지 않습니다.
* * 운영자 관리 *: Astra Control Center는 OLM(Operator Lifecycle Manager) 지원 운영자 또는 클러스터 범위 연산자와 함께 배포된 앱을 지원하지 않습니다.




== 인터넷 접속

인터넷에 대한 외부 액세스 권한이 있는지 확인해야 합니다. 그렇지 않으면 NetApp Cloud Insights에서 모니터링 및 메트릭 데이터를 수신하거나 지원 번들을 NetApp Support 사이트로 보내는 등 일부 기능이 제한될 수 있습니다.



== 라이센스

Astra Control Center의 모든 기능을 사용하려면 Astra Control Center 라이센스가 필요합니다. NetApp에서 평가판 라이센스 또는 전체 라이센스를 받으십시오. 라이센스가 없으면 다음을 수행할 수 없습니다.

* 사용자 지정 앱 정의
* 기존 앱의 스냅샷 또는 클론 생성
* 데이터 보호 정책을 구성합니다


Astra Control Center를 사용해 보고 싶다면 가능합니다 link:setup_overview.html#add-a-full-or-evaluation-license["90일 평가판 라이센스를 사용합니다"].



== 온프레미스 Kubernetes 클러스터의 서비스 유형 "로드 밸런서

Astra Control Center는 "loadbalancer"(Astra Control Center 네임스페이스의 svc/traefik) 유형의 서비스를 사용하며 액세스 가능한 외부 IP 주소를 할당해야 합니다. 온-프레미스 OpenShift 클러스터의 경우 를 사용할 수 있습니다 https://docs.netapp.com/us-en/netapp-solutions/containers/rh-os-n_LB_MetalLB.html#installing-the-metallb-load-balancer["메탈리스"^] 외부 IP 주소를 서비스에 자동으로 할당합니다. 내부 DNS 서버 구성에서 Astra Control Center에 대해 선택한 DNS 이름을 부하 분산 IP 주소로 지정해야 합니다.



== 네트워킹 요구 사항

Astra Control Center를 호스팅하는 클러스터는 다음 TCP 포트를 사용하여 통신합니다. 이러한 포트가 모든 방화벽을 통해 허용되는지 확인하고 Astra 네트워크에서 발생하는 HTTPS 송신 트래픽을 허용하도록 방화벽을 구성해야 합니다. 일부 포트에는 Astra Control Center를 호스팅하는 클러스터와 각 관리 클러스터(해당되는 경우) 간의 연결이 모두 필요합니다.

|===
| 제품 | 포트 | 프로토콜 | 방향 | 목적 


| Astra 제어 센터 | 443 | HTTPS | 침투 | UI/API 액세스 - Astra Control Center를 호스팅하는 클러스터와 관리되는 각 클러스터 간에 이 포트가 열려 있는지 확인합니다 


| Astra 제어 센터 | 9090 | HTTPS  a| 
* 수신(Astra Control Center를 호스팅하는 클러스터에)
* 송신(각 관리 클러스터의 각 작업자 노드의 노드 IP 주소에서 임의 포트)

| 메트릭 데이터를 고객에게 제공 - 각 관리 클러스터가 Astra Control Center를 호스팅하는 클러스터에서 이 포트에 액세스할 수 있는지 확인합니다 


| 트라이던트 | 34571 | HTTPS | 침투 | 노드 POD 통신 


| 트라이던트 | 9220 | HTTP | 침투 | 메트릭 엔드포인트 
|===


== 지원되는 웹 브라우저

Astra Control Center는 1280 x 720의 최소 해상도로 최신 버전의 Firefox, Safari 및 Chrome을 지원합니다.



== 다음 단계

를 봅니다 link:quick-start.html["빠른 시작"] 개요.
