---
sidebar: sidebar 
permalink: release-notes/known-issues.html 
keywords: astra, control center, bugs, known issues, problems 
summary: 알려진 문제점은 이 제품 릴리스를 성공적으로 사용하지 못하게 만들 수 있는 문제를 식별합니다. 
---
= 이 릴리스에서 알려진 문제입니다
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/release-notes/


알려진 문제점은 이 제품 릴리스를 성공적으로 사용하지 못하게 만들 수 있는 문제를 식별합니다.

현재 릴리즈에는 다음과 같은 알려진 문제가 영향을 줍니다.

*  ClusterRoleBinding created by Astra Control Center CRD during installation
*  with user-defined label goes into "removed" state
*  to stop running app backup
*  or clone fails for apps using PVCs with decimal units in Astra Control Center
*  Control Center UI slow to show changes to app resources such as persistent volume changes
*  app restore from backup Trident creates a larger PV than the original PV
*  performance impacted by large persistent volumes
*  clones fail using a specific version of PostgreSQL
*  clones fail when using Service Account level OCP Security Context Constraints (SCC)
*  buckets in Astra Control Center do not report available capacity
*  buckets between instances of Astra Control Center causes failures
*  a bucket provider type with credentials for another type causes data protection failures
*  and snapshots might not be retained during removal of an Astra Control Center instance
*  backups are retained as part of scheduled backup
* link:known-issues.html#clone-operation-cant-use-other-buckets-besides-the-default["클론 작업에서는 기본값 외에 다른 버킷을 사용할 수 없습니다"]
*  a cluster with Astra Control Center fails when default kubeconfig file contains more than one context
* link:known-issues.html#cant-determine-asup-tar-bundle-status-in-scaled-environment["스케일된 환경에서 ASUP tar 번들 상태를 확인할 수 없습니다"]
*  of Astra Control Center fails to clean up the monitoring-operator pod on the managed cluster
*  of Astra Control Center fails to clean up Traefik CRDs
*  collection stuck in a generating or uploading state




== 설치하는 동안 Astra Control Center CRD에 의해 잘못된 ClusterRoleBinding이 생성됩니다

acc-operator 버전 21.08.65가 구축된 모든 Kubernetes 클러스터에 다음 패치를 적용하십시오. 또한, acc 오퍼레이터가 재배치된 경우에도 적용해야 합니다.

이 문제를 해결하려면:

. 아래 스크립트에서 'ACC_namespace'를 사용한 네임스페이스로 바꾸십시오 link:../get-started/install_acc.html#install-astra-control-center["Astra Control Center를 구축합니다"].
+
[source, cli]
----
cat <<EOF | kubectl apply -f –
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: acc-operator-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: acc-operator-manager-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: netapp-acc-operator
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:serviceaccounts:ACC_NAMESPACE
EOF
----
. 스크립트를 실행합니다.


패치는 "ClusterRoleBinding:"acc-operator-manager-rolebinding""에서 다음 두 개의 주제를 제거합니다

[listing]
----
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:serviceaccounts
- apiGroup: ""
  kind: Group
  name: system:serviceaccounts
----


== 사용자 정의 라벨이 있는 앱은 "제거됨" 상태로 전환됩니다

k8s 레이블이 없는 앱을 정의하면 Astra Control Center에서 앱을 생성, 관리 및 즉시 제거합니다. 이를 방지하려면 Astra Control Center에서 앱을 관리하는 후 POD 및 리소스에 k8s 레이블을 추가합니다.



== 앱 백업 실행을 중지할 수 없습니다

실행 중인 백업을 중지할 방법은 없습니다. 백업을 삭제해야 하는 경우 백업이 완료될 때까지 기다린 다음 의 지침을 따르십시오 link:../use/protect-apps.html#delete-backups["백업을 삭제합니다"]. 실패한 백업을 삭제하려면 를 사용합니다 link:https://docs.netapp.com/us-en/astra-automation-2108/index.html["아스트라 API"^].



== Astra Control Center에서 PVCs를 사용하는 앱의 백업 또는 클론 생성이 실패합니다

10진수 단위로 생성된 볼륨이 Astra Control Center 백업 또는 클론 프로세스를 사용하여 실패합니다. 를 참조하십시오 link:https://kb.netapp.com/Advice_and_Troubleshooting/Cloud_Services/Astra/Backup_or_clone_may_fail_for_applications_using_PVCs_with_decimal_units_in_Astra_Control_Center["기술 자료 문서를 참조하십시오"] 를 참조하십시오.



== Astra Control Center UI는 지속적인 볼륨 변경과 같은 앱 리소스의 변경 사항을 느리게 표시합니다

데이터 보호 작업(클론, 백업, 복원)과 후속 영구 볼륨 크기 조정 후 UI에 새 볼륨 크기가 표시되기까지 최대 20분이 지연됩니다. UI에서 이러한 지연은 앱 리소스가 추가되거나 수정될 때도 발생할 수 있습니다. 이 경우 데이터 보호 작업이 몇 분 내에 성공적으로 수행되며 스토리지 백엔드에 관리 소프트웨어를 사용하여 볼륨 크기 변경을 확인할 수 있습니다.



== 백업 Trident에서 앱을 복원하는 동안 원본 PV보다 더 큰 PV가 생성됩니다

백업을 생성한 후 영구 볼륨의 크기를 조정한 다음 해당 백업에서 복원하는 경우 영구 볼륨 크기는 백업 크기를 사용하는 대신 PV의 새 크기와 일치합니다.



== 대규모 영구 볼륨의 클론 성능에 영향을 줍니다

오브젝트 저장소에 대한 클러스터 액세스에 따라 매우 크고 사용되는 영구 볼륨의 클론이 간헐적으로 느려질 수 있습니다. 클론이 멈추고 30분 이상 데이터가 복제되지 않은 경우 Astra Control이 클론 작업을 종료합니다.



== 특정 버전의 PostgreSQL을 사용하여 앱 클론이 실패합니다

동일한 클러스터 내의 앱 클론은 Bitnami PostgreSQL 11.5.0 차트와 함께 일관되게 실패합니다. 클론을 성공적으로 생성하려면 이전 또는 이후 버전의 차트를 사용하십시오.



== 서비스 계정 수준 OCP SCC(Security Context Constraints)를 사용할 때 앱 클론이 실패함

OCP 클러스터의 네임스페이스 내에서 서비스 계정 수준에서 원래 보안 컨텍스트 제약 조건이 구성된 경우 애플리케이션 클론이 실패할 수 있습니다. 애플리케이션 클론이 실패하면 Astra Control Center의 Managed Applications 영역에 상태가 "제거됨"으로 표시됩니다. 를 참조하십시오 https://kb.netapp.com/Advice_and_Troubleshooting/Cloud_Services/Astra/Application_clone_is_failing_for_an_application_in_Astra_Control_Center["기술 자료 문서를 참조하십시오"] 를 참조하십시오.



== Astra Control Center의 S3 버킷은 가용 용량을 보고하지 않습니다

Astra Control Center에서 관리하는 앱을 백업 또는 클론 생성하기 전에 ONTAP 또는 StorageGRID 관리 시스템에서 버킷 정보를 확인하십시오.



== Astra Control Center 인스턴스 간에 버킷을 재사용하면 오류가 발생합니다

다른 설치 또는 이전에 Astra Control Center에서 사용한 버킷을 재사용하려는 경우 백업 및 복구가 실패합니다. 다른 버킷을 사용하거나 이전에 사용한 버킷을 완전히 청소해야 합니다. Astra Control Center 인스턴스 간에는 버킷을 공유할 수 없습니다.



== 다른 유형에 대한 자격 증명이 있는 버킷 공급자 유형을 선택하면 데이터 보호 장애가 발생합니다

버킷을 추가할 때 해당 공급자에 맞는 자격 증명으로 올바른 버킷 공급자 유형을 선택합니다. 예를 들어, UI에서 NetApp ONTAP S3를 StorageGRID 자격 증명을 가진 유형으로 받아들이지만, 이 버킷을 사용한 이후의 모든 애플리케이션 백업 및 복원이 실패합니다.



== Astra Control Center 인스턴스를 제거하는 동안 백업 및 스냅샷이 보존되지 않을 수 있습니다

평가 라이센스가 있는 경우 ASUP를 보내지 않을 경우 Astra Control Center에 장애가 발생할 경우 데이터 손실을 방지하기 위해 계정 ID를 저장해야 합니다.



== 예약된 백업의 일부로 추가 백업이 보존됩니다

Astra Control Center에 있는 하나 이상의 백업이 백업 스케줄에 보존되도록 지정된 수를 초과하여 보존되는 경우가 있습니다. 이러한 추가 백업은 예약된 백업의 일부로 삭제되어야 하지만 삭제되지는 않으며 "보류 중" 상태로 고착됩니다. 이 문제를 해결하려면 https://docs.netapp.com/us-en/astra-automation-2108/workflows/wf_delete_backup.html["강제 삭제"] 추가 백업입니다.



== 클론 작업은 기본값 외에 다른 버킷을 사용할 수 없습니다

애플리케이션 백업 또는 애플리케이션 복구 중에 버킷 ID를 선택적으로 지정할 수 있습니다. 그러나 애플리케이션 클론 작업에서는 항상 정의된 기본 버킷을 사용합니다. 클론의 버킷을 변경할 수 있는 옵션은 없습니다. 어떤 버킷이 사용되는지 제어하려는 경우 이 두 가지 방법을 사용할 수 있습니다 link:../use/manage-buckets.html#edit-a-bucket["버킷 기본값을 변경합니다"] 또는 을 수행합니다 link:../use/protect-apps.html#create-a-backup["백업"] 뒤에 가 있습니다 link:../use/restore-apps.html["복원"] 별도.



== 기본 kubecononfig 파일에 컨텍스트가 두 개 이상 포함되어 있으면 Astra Control Center를 사용하여 클러스터를 관리할 수 없습니다

2개 이상의 클러스터와 컨텍스트를 사용하여 kubeconfig를 사용할 수 없습니다. 를 참조하십시오 link:https://kb.netapp.com/Advice_and_Troubleshooting/Cloud_Services/Astra/Managing_cluster_with_Astra_Control_Center_may_fail_when_using_default_kubeconfig_file_contains_more_than_one_context["기술 자료 문서를 참조하십시오"] 를 참조하십시오.



== 스케일된 환경에서 ASUP tar 번들 상태를 확인할 수 없습니다

ASUP 수집 과정에서 UI의 묶음 상태는 수집 또는 삭제 중 하나로 보고된다. 대규모 환경에서는 수집 시간이 최대 1시간까지 걸릴 수 있습니다. ASUP 다운로드 중에 번들의 네트워크 파일 전송 속도가 충분하지 않을 수 있으며 UI에 아무 표시 없이 15분 후에 다운로드가 시간 초과될 수 있습니다. 다운로드 문제는 ASUP 크기, 확장된 클러스터 크기 및 수집 시간이 7일 제한을 초과할 경우 등에 따라 달라집니다.



== Astra Control Center를 제거해도 관리 클러스터의 모니터링 운영자 포드가 정리되지 않습니다

Astra Control Center를 제거하기 전에 클러스터를 관리하지 않았다면 NetApp 모니터링 네임스페이스 및 네임스페이스에서 Pod를 수동으로 삭제할 수 있습니다. 이러한 명령은 다음과 같습니다.

.단계
. 'acc-monitoring' 에이전트 삭제:
+
[listing]
----
oc delete agents acc-monitoring -n netapp-monitoring
----
+
결과:

+
[listing]
----
agent.monitoring.netapp.com "acc-monitoring" deleted
----
. 네임스페이스 삭제:
+
[listing]
----
oc delete ns netapp-monitoring
----
+
결과:

+
[listing]
----
namespace "netapp-monitoring" deleted
----
. 제거된 리소스 확인:
+
[listing]
----
oc get pods -n netapp-monitoring
----
+
결과:

+
[listing]
----
No resources found in netapp-monitoring namespace.
----
. 모니터링 에이전트 제거 확인:
+
[listing]
----
oc get crd|grep agent
----
+
샘플 결과:

+
[listing]
----
agents.monitoring.netapp.com                     2021-07-21T06:08:13Z
----
. 사용자 정의 리소스 정의(CRD) 정보 삭제:
+
[listing]
----
oc delete crds agents.monitoring.netapp.com
----
+
결과:

+
[listing]
----
customresourcedefinition.apiextensions.k8s.io "agents.monitoring.netapp.com" deleted
----




== Astra Control Center를 제거해도 Traefik CRD가 정리되지 않습니다

Traefik CRD를 수동으로 삭제할 수 있습니다.

.단계
. 제거 프로세스에서 삭제되지 않은 CRD를 확인합니다.
+
[listing]
----
kubectl get crds |grep -E 'traefik'
----
+
응답

+
[listing]
----
ingressroutes.traefik.containo.us             2021-06-23T23:29:11Z
ingressroutetcps.traefik.containo.us          2021-06-23T23:29:11Z
ingressrouteudps.traefik.containo.us          2021-06-23T23:29:12Z
middlewares.traefik.containo.us               2021-06-23T23:29:12Z
serverstransports.traefik.containo.us         2021-06-23T23:29:13Z
tlsoptions.traefik.containo.us                2021-06-23T23:29:13Z
tlsstores.traefik.containo.us                 2021-06-23T23:29:14Z
traefikservices.traefik.containo.us           2021-06-23T23:29:15Z
----
. CRD 삭제:
+
[listing]
----
kubectl delete crd ingressroutes.traefik.containo.us ingressroutetcps.traefik.containo.us ingressrouteudps.traefik.containo.us middlewares.traefik.containo.us serverstransports.traefik.containo.us tlsoptions.traefik.containo.us tlsstores.traefik.containo.us traefikservices.traefik.containo.us
----




== ASUP 컬렉션이 생성 또는 업로드 상태로 고착되었습니다

ASUP 포드가 사망 또는 재시작된 경우, ASUP 수집이 생성 또는 업로드 상태로 고착될 수 있습니다. 다음을 수행합니다 link:https://docs.netapp.com/us-en/astra-automation-2108/index.html["Astra Control REST API"] 수동 수집을 다시 시작하려면 다음을 수행합니다.

[cols="25,75"]
|===
| HTTP 메소드 | 경로 


| 게시 | /accounts/{AccountID}/core/v1/ASUP 
|===

NOTE: 이 API 대안은 ASUP가 시작된 후 10분 이상 수행된 경우에만 작동합니다.



== 자세한 내용을 확인하십시오

* link:../release-notes/known-limitations.html["이 릴리스에 대해 알려진 제한 사항입니다"]

